 
---
- hosts: all
  gather_facts: no
  tasks:


  - name: Se remueve nmap en todos los servidores Linux
    ansible.builtin.yum: 
      name: nmap
      state: absent

  - name: Se define estado de SELINUX en enforcing
    selinux:
      policy: targeted
      state: enforcing

 - name: enviar mensaje via Telegram
        telegram:
          token: '789814150:AAE86c3jBVW5v2EQ2uEIZhZ_vxKIIhYXt0U'
          chat_id: 519410943
          msg: " El lanzamiento {{ tower_workflow_job_name }} ID {{ tower_workflow_job_id }} Finalizó Satisfactoriamente el {{ansible_date_time.date}} por el usuario {{ tower_user_name }} "
...
