 
---
- hosts: all
  gather_facts: no
  tasks:


  - name: Se remueve nmap en todos los servidores Linux
    ansible.builtin.yum: 
      name: nmap
      state: absent

  - name: Se define estado de SELINUX en enforcing
    selinux:
      policy: targeted
      state: enforcing

...
