---
- hosts: web
  become: true
  tasks:
  - name: Instalar httpd
    ansible.builtin.yum: 
      name: httpd
      state: present


  - name: iniciar servicio httpd 
    service:
      name: httpd
      state: started

...
