---
- hosts: all
  become: true  
  tasks:
  - name: Ejercicio1
    tower_job_template:
      name: "ej1"
      job_type: "run"
      organization: "Default"
      inventory: "Workshop Inventory"
      project: "Git"
      playbook: "ej1_attack.yml"
      credentials:
        - "Workshop Credential"
      state: "present"
      #tower_config_file: "~/tower_cli.cfg"
